name: seem-4090
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - git
  - ffmpeg
  - ninja
  - cmake
  - setuptools=68.2.2
  - wheel
  - packaging
  - cython=3.0.2
  - pytorch=2.1.0
  - torchvision=0.16.0
  - pytorch-cuda=12.1
